In [73]:
#N- Dimensional Array

import numpy as np #import numpy libary

#create an array list
scores = [44.53,34.65,2.6,90.2,87.3]
scores_array = np.array(scores)

print("Array = ",scores_array)
print("Type = ",scores_array.dtype) #.dtype returns the data type of the array

Array =  [44.53 34.65  2.6  90.2  87.3 ]
Type =  float64


In [84]:
#Nested lists with equal length will be converted into multi-dimensional array

scores_m = [[34,56,76,34],[23,54,12,11]]
scores_m_array = np.array(scores_m)

print("Array = ",scores_m_array)
print("Dimmension = ",scores_m_array.ndim) #.ndim gives you the dimensions of an array.
print("Rows, Column = ",scores_m_array.shape) #number of rows and columns
print("Type = ",scores_m_array.dtype)


Array =  [[34 56 76 34]
 [23 54 12 11]]
Dimmension =  2
Rows, Column =  (2, 4)
Type =  int32


In [87]:
#more arrays and functions
x = np.zeros(5)
y = np.ones(5)

np.zeros((4,3)) #mention the shape of the area (4 rows  by 3 columns)
np.arange(15) #the array is the number range: 1, 2, 3....14


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [91]:
#call scores from above in the below scenario.
scores_array

print("A: ",scores_array * scores_array)
print("B: ",scores_array - scores_array)
print("C: ",1/scores_array)
print("D: ",scores_array ** 0.5)

A:  [1.9829209e+03 1.2006225e+03 6.7600000e+00 8.1360400e+03 7.6212900e+03]
B:  [0. 0. 0. 0. 0.]
C:  [0.02245677 0.02886003 0.38461538 0.01108647 0.01145475]
D:  [6.67308025 5.88642506 1.61245155 9.49736806 9.3434469 ]
