In [26]:
import numpy as np
from numpy import random
algebra = random.rand(7,4) #4 columns by 7 rows.
for i in range (7):
    algebra[i] = i
algebra

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.]])

In [16]:
#Select a subset of rows in a particular order
algebra[[4,5,1]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [1., 1., 1., 1.]])

In [33]:
#Transposing Arrays
transpose = np.arange(12).reshape(3,4)
print(transpose)
transpose.T #the shape changes to 4,3

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [34]:
#you can use np.dot function to perform matrix computations. You can calculate X transpose X as follows:
np.dot(transpose.T, transpose)

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])