In [2]:
import numpy as np
from numpy import random

lp = np.random.randn(8)
print(lp)
lp.sort()
lp

[ 0.18057371 -0.98266634 -0.29388933 -0.33210748 -0.13937695 -0.40066722
 -1.06733515 -0.51051647]


array([-1.06733515, -0.98266634, -0.51051647, -0.40066722, -0.33210748,
       -0.29388933, -0.13937695,  0.18057371])

In [3]:
tp = np.random.randn(4,4)
tp

array([[-0.41444767, -1.42705905,  1.9416425 , -2.29639435],
       [-0.91174822, -1.72642033, -0.71086123, -0.97277868],
       [ 0.83912635,  0.09618549, -0.2797014 , -0.1767063 ],
       [-0.44757049,  0.18798075,  0.84246394, -0.28553845]])

In [9]:
tp.sort(1) #check the rows are sorted
tp

array([[-2.29639435, -1.42705905, -0.41444767,  1.9416425 ],
       [-1.72642033, -0.97277868, -0.91174822, -0.71086123],
       [-0.2797014 , -0.1767063 ,  0.09618549,  0.83912635],
       [-0.44757049, -0.28553845,  0.18798075,  0.84246394]])

In [27]:
person = np.array(['Manu','John','Chris','David','Luke','David'])
np.unique(person) #returns unique elements in the array
#set(person) #alternatibe to unique function
np.in1d(person,['Chris']) #Checks the values for the variable and returns "True" once found and "False" for all others.

print("""Other Functions are: 
intersect1d(x, y)-> Compute the sorted, common elements in x and y
union1d(x,y) -> compute the sorted union of elements
setdiff1d(x,y) -> set difference, elements in x that are not in y
setxor1d(x, y) -> Set symmetric differences; elements that are in either of the arrays, but not both""")

Other Functions are: 
intersect1d(x, y)-> Compute the sorted, common elements in x and y
union1d(x,y) -> compute the sorted union of elements
setdiff1d(x,y) -> set difference, elements in x that are not in y
setxor1d(x, y) -> Set symmetric differences; elements that are in either of the arrays, but not both
