In [8]:
import numpy as np
from numpy import random
from numpy.linalg import inv, qr # numpy.linalg has standard matrix operations like determinants and inverse.

In [4]:
cp = np.array([[1,2,3],[4,5,6]])
dp = np.array([[7,8],[9,10],[11,12]])
print("CP Array:\n{}".format(cp))
print("DP Array:\n{}".format(dp))

CP Array:
[[1 2 3]
 [4 5 6]]
DP Array:
[[ 7  8]
 [ 9 10]
 [11 12]]


In [6]:
#What are these doing? 
cp.dot(dp)
np.dot(cp,np.ones(3))

array([ 6., 15.])

In [9]:
#Linear Algebra Numpy Function
#Utilize cp above.
new1 = cp.T.dot(cp) #multiply cp inverse and cp. Element wise multiplication.
print(new1)

[[17 22 27]
 [22 29 36]
 [27 36 45]]


In [11]:
sp = np.random.randn(5,5)
print(inv(sp))
rt = inv(sp)

[[-0.51474994  0.04081855  1.07781177 -0.43635401 -0.04144685]
 [ 0.43415314 -0.11699364 -0.71684333 -0.00648151  0.25278688]
 [-0.10069316  0.02293722 -0.47967713  0.0273027   0.16892674]
 [ 0.09907678  0.1895648   0.31806403 -0.06614568  0.34853995]
 [ 0.44234148  0.34494795 -0.06135194 -0.46757704 -0.36082392]]


In [12]:
#To calculate the product of a matrix and its inverse
sp.dot(rt)

array([[ 1.00000000e+00,  5.74003469e-18,  4.85847568e-17,
         1.46271592e-18,  1.50246429e-17],
       [-3.68209782e-17,  1.00000000e+00,  3.93880454e-16,
        -1.56136429e-16,  7.14485170e-17],
       [ 3.08273815e-18,  4.11209050e-18,  1.00000000e+00,
         8.48436674e-18,  6.67858303e-18],
       [-2.16642919e-17, -7.12078732e-18,  2.92410071e-16,
         1.00000000e+00,  3.48669008e-17],
       [-2.67568141e-17,  7.11874986e-17,  9.30933227e-17,
        -1.25846310e-16,  1.00000000e+00]])

In [13]:
q,r=qr(sp)
print(q)
r

print("""Other Matrix Functions

diag : Return the diagonal (or off-diagonal) elements of a square matrix as a 1D array, or convert a 1D array into a square
matrix with zeros on the off-diagonal
trace: Compute the sum of the diagonal elements
det: Compute the matrix determinant
eig: Compute the eigenvalues and eigenvectors of a square matrix
pinv: Compute the pseudo-inverse of a square matrix
svd: Compute the singular value decomposition (SVD)
solve: Solve the linear system Ax = b for x, where A is a square matrix
lstsq: Compute the least-squares solution to y = Xb""")

[[-0.21007897  0.78978767 -0.01870349  0.19623005 -0.54152212]
 [-0.57075563 -0.52595772  0.28948946  0.36806579 -0.42229127]
 [ 0.03923831 -0.10767912 -0.781916    0.6081379   0.07510811]
 [-0.7701664   0.21801658 -0.11755215 -0.13354392  0.57241593]
 [ 0.18817254  0.20119116  0.53910565  0.66208432  0.4417269 ]]


array([[ 2.19588007,  2.67753244, -0.03257185, -1.37974866, -0.24593594],
       [ 0.        ,  1.8830371 , -2.61840906, -0.16347928, -0.62213854],
       [ 0.        ,  0.        ,  2.12111353,  0.79131494,  0.26331961],
       [ 0.        ,  0.        ,  0.        ,  1.91483889,  0.01472612],
       [ 0.        ,  0.        ,  0.        ,  0.        , -1.22421736]])