In [1]:
import numpy as np
from numpy import random

stats = np.random.randn(5,5)
print(stats.mean()) #calculates the mean of stats
print(np.mean(stats)) #alternative method to cal mean
print(stats.sum())

0.02547243393920628
0.02547243393920628
0.636810848480157


In [22]:
py = np.arange(12).reshape(4,3)
print("The arrays are:\n {}".format(py))
print("The sum of rows are:\n {}".format(np.sum(py,axis =0)))
print("\n",py.sum()) #sum of all numbers
print("\n",py.sum(1)) #sum of all numbers from left to right
print(py.sum(0)) #sum of all numbers from top to down
print("\nTop to down:\n",py.cumsum((0))) #cummulative sum top to down
print("\n Left to right:\n",py.cumsum(1))

The arrays are:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
The sum of rows are:
 [18 22 26]

 66

 [ 3 12 21 30]
[18 22 26]

Top to down:
 [[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]
 [18 22 26]]

 Left to right:
 [[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]
 [ 9 19 30]]


In [112]:
xp = np.random.randn(100)
print((xp > 0).sum()) #sum of all positive values
print((xp < 0).sum()) #um of all negative values
tandf =np.array([True,False,True,False,True,False])
print(tandf.any()) #check if any of the values are true
print(tandf.all()) #returns false even if a single value is false

print("""\nOther array functions are:
std, var -> standard deviation and variance
min, max -> Minimum and Maximum
argmin, argmax -> Indices of minimum and maximum elements""")

64
36
True
False

Other array functions are:
std, var -> standard deviation and variance
min, max -> Minimum and Maximum
argmin, argmax -> Indices of minimum and maximum elements
